//Add Moves
export const ADD_MOVE = 'ADD_MOVE';
export const ADD_MOVE_SUCCESS = 'ADD_MOVE_SUCCESS';
export const ADD_MOVE_ERROR = 'ADD_MOVE_ERROR';

//Download Moves
export const DOWNLOAD_MOVES = 'DOWNLOAD_MOVES';
export const DOWNLOAD_SUCCESS = 'DOWNLOAD_SUCCESS';
export const DOWNLOAD_ERROR = 'DOWNLOAD_ERROR';

//Delete Moves
export const DELETE_MOVE = 'DELETE_MOVE';
export const DELETE_MOVE_SUCCESS = 'DELETE_MOVE_SUCCESS';
export const DELETE_MOVE_ERROR = 'DELETE_MOVE_ERROR';

//Edit Moves
export const EDIT_MOVE = 'EDIT_MOVE';
export const EDIT_MOVE_START = 'EDIT_MOVE_START'
export const EDIT_MOVE_SUCCESS = 'EDIT_MOVE_SUCCESS';
export const EDIT_MOVE_ERROR = 'EDIT_MOVE_ERROR';

//Games
export const BEGIN_GAME = 'BEGIN_GAME';
export const BEGIN_GAME_SUCCESS = 'BEGIN_GAME_SUCCESS';
export const BEGIN_GAME_ERROR = 'BEGIN_GAME_ERROR ';

//Insert Rounds on Game
export const INSERT_ROUNDS_START = 'INSERT_ROUNDS_START';
export const INSERT_ROUNDS_SUCCESS = 'INSERT_ROUNDS_SUCCESS';
export const INSERT_ROUNDS_ERROR = 'INSERT_ROUNDS_ERROR';

//End Game
export const END_GAME = 'END_GAME';

//Download Stats
export const MOST_PICKED_FIRST = 'MOST_PICKED_FIRST';
export const MOST_PICKED_FIRST_SUCCESS = 'MOST_PICKED_FIRST_SUCCESS';
export const MOST_PICKED_FIRST_ERROR = 'MOST_PICKED_FIRST_ERROR';

export const AVERAGE_TIME_GAME = 'AVERAGE_TIME_GAME';
export const AVERAGE_TIME_GAME_SUCCESS = 'AVERAGE_TIME_GAME_SUCCESS';
export const AVERAGE_TIME_GAME_ERROR = 'AVERAGE_TIME_GAME_ERROR';

export const AVERAGE_Q_TAKES_COMPLETE = 'AVERAGE_Q_TAKES_COMPLETE';
export const AVERAGE_Q_TAKES_COMPLETE_SUCCESS = 'AVERAGE_Q_TAKES_COMPLETE_SUCCESS';
export const AVERAGE_Q_TAKES_COMPLETE_ERROR = 'AVERAGE_Q_TAKES_COMPLETE_ERROR';

export const PERCENTAGE_COMPLETE_INCOMPLETE = 'PERCENTAGE_COMPLETE_INCOMPLETE';
export const PERCENTAGE_COMPLETE_INCOMPLETE_SUCCESS = 'PERCENTAGE_COMPLETE_INCOMPLETE_SUCCESS';
export const PERCENTAGE_COMPLETE_INCOMPLETE_ERROR = 'PERCENTAGE_COMPLETE_INCOMPLETE_ERROR';




